apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fastapi-film
  labels:
    app: film
data:
  default.conf: |
    upstream film_project {
        server film-service:5000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://film_project;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }