"""create table film and utilisateur

Revision ID: 37e06c3283a8
Revises: 
Create Date: 2023-06-06 16:58:24.116746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e06c3283a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=256), nullable=True),
    sa.Column('nom', sa.String(length=256), nullable=True),
    sa.Column('permissions', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String((256)), nullable=False),
    sa.Column('hashed_motDePasse', sa.String((256)), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=False)
    op.create_index(op.f('ix_utilisateur_id'), 'utilisateur', ['id'], unique=False)
    
    
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=256), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=False),
    sa.Column('synopsis', sa.String(length=256), nullable=True),
    sa.Column('genre', sa.String(length=256), nullable=True),
    sa.Column('realisateur', sa.String(length=256), nullable=True),
    sa.Column('acteurs', sa.String(length=256), nullable=True),
    sa.Column('classification', sa.String(length=256), nullable=True),
    sa.Column('realisateur', sa.String(length=256), nullable=True),
    sa.Column('urlBandeAnnonce', sa.String(length=256), nullable=True),
    sa.Column('urlAffiche', sa.String(length=256), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_id'), 'film', ['id'], unique=False)
    op.create_index(op.f('ix_film_urlBandeAnnonce'), 'film', ['urlBandeAnnonce'], unique=False)
    
    
    op.create_table('seance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('heure', sa.Integer(), nullable=False),
    sa.Column('tarifs', sa.Integer(), nullable=False),
    sa.Column('id_film', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_film'], ['film.id'], ),
    sa.Column('id_salle', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_salle'], ['salle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seance_id'), 'seance', ['id'], unique=False)
    op.create_index(op.f('ix_seance_date'), 'seance', ['date'], unique=False)
    
    
    op.create_table('salle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=256), nullable=True),
    sa.Column('capacite', sa.Integer(), nullable=False),
    sa.Column('equipements', sa.String(length=256), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salle_id'), 'salle', ['id'], unique=False)
    op.create_index(op.f('ix_salle_nom'), 'salle', ['nom'], unique=False)
    
    
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siegesReserves', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('id_seance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_seance'], ['seance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_id'), 'reservation', ['id'], unique=False)
    op.create_index(op.f('ix_reservation_siegesReserves'), 'reservation', ['siegesReserves'], unique=False)
    
    
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=256), nullable=True),
    sa.Column('prenom', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('dateNaissance', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('abonnement', sa.String(), nullable=False),
    sa.Column('carteFidelite', sa.String(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )  
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_index(op.f('ix_client_nom'), 'client', ['nom'], unique=False)
    
    
    op.create_table('siege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nbreSieges', sa.Integer(), nullable=False),
    sa.Column('typeSieges', sa.String(length=256), nullable=True),
    sa.Column('id_salle', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_salle'], ['salle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )  
    op.create_index(op.f('ix_siege_id'), 'siege', ['id'], unique=False)
    op.create_index(op.f('ix_siege_nbreSieges'), 'siege', ['nbreSieges'], unique=False)
    
    
    
    # ### end Alembic commands ###


def downgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_url'), table_name='film')
    op.drop_index(op.f('ix_film_id'), table_name='film')
    op.drop_table('film')
    op.drop_index(op.f('ix_utilisateur_id'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('user')
    # # ### end Alembic commands ###
    ...