apiVersion: apps/v1
kind: Deployment
metadata:
  name: film-deployment
  namespace: fastapi-film
  labels:
    app: film
spec:
  replicas: 3
  selector:
    matchLabels:
      app: film-app
  template:
    metadata:
      labels:
        app: film-app
    spec:
      initContainers:
        - name: init-postgres-service
          image: postgres:10.17
          command: ['sh', '-c','until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
        - image: mukulmantosh/film-fastapi:latest
          imagePullPolicy: Always
          name: sample-container
          envFrom:
          - secretRef:
              name: film-secret
          ports:
            - containerPort: 8001
              name: fastapi
          readinessProbe:
            httpGet:
              port: 8001
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 8001
              path: /docs
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"